SELECT TOP 10 * FROM olist_customers_dataset
SELECT TOP 10 * FROM olist_geolocation_dataset
SELECT TOP 10 * FROM olist_order_items_dataset
SELECT TOP 10 * FROM olist_order_payments_dataset
SELECT TOP 10 * FROM olist_order_reviews_dataset
SELECT TOP 10 * FROM olist_orders_dataset
SELECT TOP 10 * FROM olist_products_dataset
SELECT TOP 10 * FROM olist_sellers_dataset
SELECT TOP 10 * FROM product_category_name_translation