SELECT TOP 10 * FROM olist_customers_dataset

CREATE TABLE TB_ACT_olist_customers_dataset
(

CUSTOMER_ID NVARCHAR(150),
CUSTOMER_UNIQUE_ID NVARCHAR(150),
CUSTOMER_ZIP_CODE_PREFIX NVARCHAR(15),
CUSTOMER_CITY NVARCHAR(100),
CUSTOMER_STATE CHAR(2)

)
INSERT INTO TB_ACT_olist_customers_dataset
SELECT * FROM olist_customers_dataset

CREATE TABLE TB_ACT_olist_orders_dataset
(

ORDER_ID NVARCHAR(150),
CUSTOMER_ID NVARCHAR(150),
ORDER_STATUS NVARCHAR(150),
ORDER_PURCHASE_TIMESTAMP NVARCHAR(200),
ORDER_APPROVED_AT NVARCHAR(200),
ORDER_DELIVERED_CARRIER_DATE NVARCHAR(200),
ORDER_DELIVERED_CUSTOMER_DATE NVARCHAR(200),
ORDER_ESTIMATED_DELIVERED_DATE NVARCHAR(200)

)
INSERT INTO TB_ACT_olist_orders_dataset
SELECT * FROM olist_orders_dataset



SELECT * FROM TB_ACT_olist_customers_dataset

-- Quais Clientes fizeram pedidos? --

SELECT * FROM TB_ACT_olist_customers_dataset

SELECT * FROM TB_ACT_olist_orders_dataset

UPDATE [TB_ACT_olist_orders_dataset] SET [ORDER_DELIVERED_CARRIER_DATE] = NULL
WHERE [ORDER_DELIVERED_CARRIER_DATE]= ''

UPDATE [TB_ACT_olist_orders_dataset] SET [ORDER_DELIVERED_CUSTOMER_DATE] = NULL
WHERE [ORDER_DELIVERED_CUSTOMER_DATE]= ''

CREATE VIEW VW_PEDIDOS_POR_CLIENTES
AS

SELECT O.*, C.CUSTOMER_CITY, C.CUSTOMER_STATE
FROM TB_ACT_olist_orders_dataset AS O
INNER JOIN TB_ACT_olist_customers_dataset AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID

SELECT * FROM VW_PEDIDOS_POR_CLIENTES


